version: "3.3"
services: 
    proxy:
        image: mitmproxy/mitmproxy:${MITMVER}
        labels: 
            - mitmproxy
        env_file: 
            - .env
        volumes: 
            - ${PWD}/plugins:${MITMHOME}/plugins
            - ${PWD}/certs:${MITMHOME}/.mitmproxy
            - ${PWD}/logs:${MITMHOME}/logs
            - ${PWD}/entrypoint.sh:/usr/local/bin/entrypoint.sh
        ports: 
            - "8080:8080"
            - "8081:8081"
        command: >
            sh -c "chmod +x /usr/local/bin/entrypoint.sh &&
            /usr/local/bin/entrypoint.sh"